# Generated by Django 4.0.1 on 2022-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='tour_guide_images/'),
        ),
    ]
