# Generated by Django 4.0.1 on 2022-04-14 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('brief_info', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('policy', models.TextField(max_length=10000)),
                ('terms_and_condition', models.TextField(max_length=10000)),
                ('is_verified', models.BooleanField(default=False)),
                ('information_added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
