# Generated by Django 4.0.1 on 2022-04-15 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_city_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_vendor', '0002_carvendorprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_average', models.FloatField()),
                ('driver', models.BooleanField(default=False)),
                ('rent_with_driver', models.IntegerField(default=0)),
                ('rent_without_driver', models.IntegerField(default=0)),
                ('picture', models.FileField(blank=True, upload_to='vendor_trip/')),
                ('is_verified', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
