# Generated by Django 4.0.1 on 2022-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripvendorprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='trip_vendor_images/'),
        ),
    ]
