# Generated by Django 4.0.1 on 2022-04-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_vendor', '0002_alter_tripvendorprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripvendorprofile',
            name='picture',
            field=models.FileField(blank=True, upload_to='trip_vendor_images/'),
        ),
    ]
