# Generated by Django 4.0.1 on 2022-04-15 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_city_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_vendor', '0003_alter_tripvendorprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accommodation', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('guide', models.BooleanField(default=False)),
                ('other_expenses', models.BooleanField(default=False)),
                ('departure_info', models.CharField(max_length=255)),
                ('services_included', models.TextField(max_length=10000)),
                ('services_not_included', models.TextField(max_length=10000)),
                ('picture', models.FileField(blank=True, upload_to='vendor_trip/')),
                ('is_verified', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TripDepartureCity', to='home.city')),
                ('trip_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TripArrivalCity', to='home.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
