# Generated by Django 4.0.1 on 2022-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_vendor', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_price_per_person',
            field=models.IntegerField(default=0),
        ),
    ]
