# Generated by Django 4.0.1 on 2022-01-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=255)),
                ('to_place', models.CharField(max_length=255)),
                ('vehicle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(max_length=255)),
                ('persons', models.IntegerField()),
                ('budget_spent', models.IntegerField()),
                ('budget_spent_food', models.IntegerField()),
                ('budget_spent_hotel', models.IntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='campaign/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
