# Generated by Django 4.0.1 on 2022-01-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetrip',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sharetrip',
            name='image',
            field=models.FileField(null=True, upload_to='trips/'),
        ),
    ]
