# Generated by Django 4.0.1 on 2022-04-13 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0002_alter_sharetrip_date_alter_sharetrip_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharetrip',
            old_name='heading',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sharetrip',
            name='budget_spent',
        ),
        migrations.RemoveField(
            model_name='sharetrip',
            name='budget_spent_hotel',
        ),
        migrations.RemoveField(
            model_name='sharetrip',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='sharetrip',
            name='to_place',
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='budget_spent_accommodation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='budget_spent_travelling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DepartureCity', to='home.city'),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ArrivalCity', to='home.city'),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='total_budget_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharetrip',
            name='trip_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sharetrip',
            name='budget_spent_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sharetrip',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='sharetrip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
