# Generated by Django 4.0.1 on 2022-04-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_rename_heading_sharetrip_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharetrip',
            old_name='created',
            new_name='shared_on',
        ),
    ]
