# Generated by Django 4.0.1 on 2022-04-13 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_rename_created_sharetrip_shared_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetrip',
            name='shared_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
