# Generated by Django 4.0.1 on 2022-04-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0007_managementrolerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementrolerequest',
            old_name='is_verified',
            new_name='role_given',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
