# Generated by Django 4.0.1 on 2022-04-14 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0008_rename_is_verified_managementrolerequest_role_given_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagementRoleRequest',
            new_name='RoleElevationRequest',
        ),
    ]
