# Generated by Django 4.0.1 on 2022-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_rename_managementrolerequest_roleelevationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(default='aksndoa', max_length=255),
            preserve_default=False,
        ),
    ]
